# 1. Aşama: Build
FROM node:20-alpine AS builder

WORKDIR /app

# Ana dizinden frontend klasörünün içine bakmasını söylüyoruz
COPY frontend/package*.json ./
RUN npm install

# Tüm frontend kodunu kopyala ve derle
COPY frontend/ ./
RUN npm run build

# 2. Aşama: Production Nginx
FROM nginx:alpine

RUN sed -i 's/listen[[:space:]]*80;/listen 8080;/g' /etc/nginx/conf.d/default.conf

# Derlenen dosyaları kopyala
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 8080